---
#
- name: deploy account
  template: src=account.py  dest=/home/ubuntu/python/scrapy-zhihu/zhihu/account.py

- name: deploy setting
  template: src=settings.py dest=/home/ubuntu/python/scrapy-zhihu/zhihu/settings.py

- name: delete default setting
  shell: rm -rf conf.d chdir=/etc/scrapyd
  sudo: yes

- name: edit scrapyd conf
  template: src=scrapyd.conf dest=/etc/scrapyd/scrapyd.conf
  sudo: yes

- name: edit scrapyd conf
  template: src=scrapyd.conf dest=/home/ubuntu/.scrapyd.conf

- name: start scrapyd
  service: name=scrapyd state=restarted
  sudo: yes

- name: deploy spider
  shell: scrapyd-deploy scrapyd2 -p zhihu chdir=/home/ubuntu/python/scrapy-zhihu
  
